/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as EspaceRouteImport } from './routes/espace'
import { Route as CallbackRouteImport } from './routes/callback'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as EspaceAuthenticatedRouteImport } from './routes/espace/authenticated'

const EspaceRoute = EspaceRouteImport.update({
  id: '/espace',
  path: '/espace',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const EspaceAuthenticatedRoute = EspaceAuthenticatedRouteImport.update({
  id: '/authenticated',
  path: '/authenticated',
  getParentRoute: () => EspaceRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/callback': typeof CallbackRoute
  '/espace': typeof EspaceRouteWithChildren
  '/espace/authenticated': typeof EspaceAuthenticatedRoute
}
export interface FileRoutesByTo {
  '/callback': typeof CallbackRoute
  '/espace': typeof EspaceRouteWithChildren
  '/espace/authenticated': typeof EspaceAuthenticatedRoute
  '/': typeof PublicIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicRouteWithChildren
  '/callback': typeof CallbackRoute
  '/espace': typeof EspaceRouteWithChildren
  '/espace/authenticated': typeof EspaceAuthenticatedRoute
  '/_public/': typeof PublicIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/callback' | '/espace' | '/espace/authenticated'
  fileRoutesByTo: FileRoutesByTo
  to: '/callback' | '/espace' | '/espace/authenticated' | '/'
  id:
    | '__root__'
    | '/_public'
    | '/callback'
    | '/espace'
    | '/espace/authenticated'
    | '/_public/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicRoute: typeof PublicRouteWithChildren
  CallbackRoute: typeof CallbackRoute
  EspaceRoute: typeof EspaceRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/espace': {
      id: '/espace'
      path: '/espace'
      fullPath: '/espace'
      preLoaderRoute: typeof EspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/espace/authenticated': {
      id: '/espace/authenticated'
      path: '/authenticated'
      fullPath: '/espace/authenticated'
      preLoaderRoute: typeof EspaceAuthenticatedRouteImport
      parentRoute: typeof EspaceRoute
    }
  }
}

interface PublicRouteChildren {
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

interface EspaceRouteChildren {
  EspaceAuthenticatedRoute: typeof EspaceAuthenticatedRoute
}

const EspaceRouteChildren: EspaceRouteChildren = {
  EspaceAuthenticatedRoute: EspaceAuthenticatedRoute,
}

const EspaceRouteWithChildren =
  EspaceRoute._addFileChildren(EspaceRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PublicRoute: PublicRouteWithChildren,
  CallbackRoute: CallbackRoute,
  EspaceRoute: EspaceRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
